spring:
  application:
    name: portal
  datasource:
    url: jdbc:postgresql://127.0.0.1:5431/dev
    username: ahavah
    password: password
  flyway:
    baseline-on-migrate: true
    clean-disabled: false
  jpa:
    show-sql: true
server:
  port: 8888

jwt:
  secret: ${JWT_SECRET}
  access_expiry: 86400
  refresh_expiry: 86400